### ISSUE TITLE
http header authorisation

### ISSUE THREAD

**Issue by Russsgithub** [francisli/processing-restclient#10]
Is it possible to use http header authorisation with this library .OAuth seems to fail to authorise.
Thanks

**Comment by francisli** [comment]
It is now possible to set arbitrary HTTP headers (http://francisli.github.io/processing-restclient/RESTClient_setHeader_.html). There's also a convenience helper for setting the typical OAuth2 authorization bearer token (http://francisli.github.io/processing-restclient/RESTClient_setBearerAuthorizationHeader_.html).
