### ISSUE TITLE
Not sure how to install the library

### ISSUE THREAD

**Issue by LabanaTech** [francisli/processing-restclient#11]
Hello,

  I would like to get a copy of my processing sketch, and send it to tweeter as a picture.

  I understand that your sketch does exactly that, but I don't really understand how to / what to install in the library to make it run. Could you please explain me how it works?

 Thank you very much!

**Comment by francisli** [comment]
Download the latest restclient.zip from here:

https://github.com/francisli/processing-restclient/releases/latest

Unzip the file, and copy/move the restclient folder into your Processing/libraries folder. Restart Processing, and restclient should appear in the Libraries menu for inclusion in your sketches.
