### ISSUE TITLE
problem with this library and processing 3

### ISSUE THREAD

**Issue by shirish47** [francisli/processing-restclient#12]
`import com.francisli.processing.http.*;

HttpClient c;
void setup()
{
 request();
}
void draw()
{}

void request()
{

  c= new HttpClient(this,"127.0.0.1",9090);
  c.GET("/submit/data");

}
void responseReceived(HttpRequest request, HttpResponse response) {
println(response.getContentAsString());
}`

shows an error
as 
NosuchmethodError: you may be using library that is incompatible to this version of processing .:(

**Comment by francisli** [comment]
This library has been updated for Processing 3 with its renaming to RESTClient...
